name: Publish to MCP Registry

on:
  workflow_run:
    workflows: ["Publish to npm"]
    types:
      - completed

jobs:
  publish:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install mcp-publisher
        run: |
          brew install mcp-publisher || curl -L https://github.com/modelcontextprotocol/registry/releases/latest/download/mcp-publisher-linux-amd64 -o /usr/local/bin/mcp-publisher
          chmod +x /usr/local/bin/mcp-publisher

      - name: Publish to MCP Registry
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mcp-publisher login github
          mcp-publisher publish
